services: 
  app:
    build: .
    container_name: My_FastAPI_project
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "123456789"
      DB_NAME: "my_db"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
      SECRET_KEY: "SECRET_key" 
      PYTHONPATH: /app
    volumes: 
      - .:/app
    
  db:
    image: postgres:14
    container_name: postgres_Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: my_db
    volumes:
      - pg_data:/var/lib/postgresql/data  
  
  cache:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/data
  
volumes:
  pg_data:
  redis_data: