"""Add is_super column

Revision ID: f9fe14b0b277
Revises: 4ca168aa7b66
Create Date: 2024-11-27 16:31:02.794425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fe14b0b277'
down_revision: Union[str, None] = '4ca168aa7b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pictures_user_id_key', 'pictures', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pictures_user_id_key', 'pictures', ['user_id'])
    # ### end Alembic commands ###
